routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
// Route::get('/storage/{extra}', function ($extra) {
//     return redirect("/public/storage/$extra");
//     })->where('extra', '.*');
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

     //change password
     Route::get('change-password', 'Admin\ChangePasswordController@create')->name('password.create');
     Route::post('change-password', 'Admin\ChangePasswordController@update')->name('password.update');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');

    // subjects
    Route::get('subjects/getspecificgrades','Admin\SubjectController@getGrades')->name('subjects.getspecificgrades');
    Route::delete('subjects/destroy', 'Admin\SubjectController@massDestroy')->name('subjects.massDestroy');
    Route::resource('subjects','Admin\SubjectController');

    // questions
    Route::delete('questions/destroy', 'Admin\QuestionController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions','Admin\QuestionController');
    Route::get('questions/download/{file}','Admin\QuestionController@download')->name('questions.download');

    // answers
    Route::get('answers/getspecificsubjects','Admin\AnswerController@getSubjects')->name('answers.getspecificsubjects');
    Route::get('answers/getsubject','Admin\AnswerController@getSubject')->name('answers.getsubject');
    Route::delete('answers/destroy', 'Admin\AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers','Admin\AnswerController');
    Route::get('answers/download/{file}','Admin\AnswerController@download')->name('answers.download');
    Route::post('answers/upload','Admin\AnswerController@uploaded')->name('answers.uploaded');
    Route::get('answers/upload/{hash}','Admin\AnswerController@tusUpload')->name('answers.tus');

    // programs
    Route::delete('programs/destroy', 'Admin\ProgramController@massDestroy')->name('programs.massDestroy');
    Route::resource('programs', 'Admin\ProgramController');

    // form
    Route::delete('forms/destroy', 'Admin\FormController@massDestroy')->name('forms.massDestroy');
    Route::resource('forms', 'Admin\FormController');
    Route::get('forms/{form}', 'Admin\FormController@generateform')->name('forms.generate');
    Route::get('forms/{form}/print', 'Admin\FormController@printform')->name('forms.print');
    Route::post('forms/print', 'Admin\FormController@printmultipleform')->name('forms.print.multiple');
    Route::post('forms/triplicate/print', 'Admin\FormController@printtriplicate')->name('forms.print.triplicate');
    Route::get('forms/{form}/print-studentdetails', 'Admin\FormController@printformdetails')->name('forms.print-student-details');
    Route::post('forms/print-studentdetails', 'Admin\FormController@printmultipleformdetails')->name('forms.print-multiple-student-details');

    Route::resource('faculty', 'Admin\FacultyController');
    Route::delete('faculties/destroy', 'Admin\FacultyController@massDestroy')->name('faculty.massDestroy');

    Route::get('levels/getspecificlevels','Admin\LevelsController@getlevels')->name('levels.getspecificlevels');
    Route::delete('levels/destroy', 'Admin\LevelsController@massDestroy')->name('levels.massDestroy');
    Route::resource('levels', 'Admin\LevelsController');
    Route::post('levels/addlevel','Admin\LevelsController@addLevel')->name('levels.addLevel');

    // Route::post('programtypes/addtype','ProgramTypesController@addType')->name('programtypes.addType');
    // Route::delete('programtypes/destroy', 'ProgramTypesController@massDestroy')->name('programtypes.massDestroy');
    // Route::resource('programtypes', 'ProgramTypesController');

    Route::get('courses/getspecificcourses','Admin\CoursesController@getCourses')->name('courses.getspecificcourses');
    Route::get('courses/getcoursetypes','Admin\CoursesController@getCourseTypes')->name('courses.getcoursetypes');
    Route::delete('courses/destroy', 'Admin\CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'Admin\CoursesController');
    // Route::post('programs/addprogram','Admin\ProgramsController@addProgram')->name('programs.addProgram');

    Route::get('subs/getspecificsubs','Admin\SubController@getSubs')->name('subs.getspecificsubs');
    Route::get('subs/getspecificsub','Admin\SubController@getSub')->name('subs.getspecificsub');
    Route::delete('subs/destroy', 'Admin\SubController@massDestroy')->name('subs.massDestroy');
    Route::resource('subs','Admin\SubController', [
        'except' => [ 'create' ]
    ]);
    Route::get('subs/create/{id}','Admin\SubController@create')->name('subs.create');
    Route::get('subs/{id}/list', 'Admin\SubController@courseSubjects')->name('subs.courseSubjects');


});

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Answer extends Model
{
    use SoftDeletes;

    protected $dates = [
      'created_at',
      'updated_at',
      'deleted_at',
  ];

  protected $append = [
      'hash',
      'expired'
  ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'admin_id','subject_id', 'files', 'is_uploaded' , 'created_at', 'updated_at', 'deleted_at',
    ];


    public function subject() {
       return $this->belongsTo(Subject::class);
    }

    public function user() {
       return $this->belongsTo(Admin::class,'admin_id');
    }
}

app/Http/Controllers/Admin/AnswerController.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use Gate;
use Session;
use App\Answer;
use App\Program;
use App\Subject;
use \Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Crypt;
use App\Http\Requests\StoreAnswerRequest;
use App\Http\Requests\UpdateAnswerRequest;
use Symfony\Component\HttpFoundation\Response;
use App\Http\Requests\MassDestroyAnswerRequest;
use Illuminate\Contracts\Encryption\DecryptException;

class AnswerController extends Controller
{

     public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        abort_if(Gate::denies('answer-access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $auth_roles = Auth::user()->roles()->pluck('title');
        $admin = Auth::user()->id;

        //getting only accessible answers for user group
        foreach($auth_roles as $key => $role){
            if($role == 'IT Admin' || $role == 'Admin'){
                $answers = Answer::with('subject')->get();
                break;
            }
            else{
                $answers = Answer::where('admin_id',$admin)->with('subject')->get();
            }
        }
        foreach ($answers as $answer) {
            $startTime = Carbon::now();
            $endTime = Carbon::parse($answer->subject->deadline);
            $timeRemaining = $endTime->diffForHumans($startTime);
            // dd($timeRemaining);
            if(str_contains($timeRemaining,'before')){
                $answer->expired = 1;
            }
            $answer->hash = Crypt::encrypt($answer->id);
        }
        // dd($answers);
        return view('admin.backend.answers.index', compact('answers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        abort_if(Gate::denies('answer-create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $programs = Program::pluck('title','id')->prepend('Please select a program','');
        return view('admin.backend.answers.create', compact('programs'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreAnswerRequest $request)
    {
        // dd($request->all());
        $current = Carbon::now();
        $subject = Subject::findOrFail($request->subject_id);
        $deadline = $subject->deadline;

        if(!$deadline || $current < $deadline) {
            // if subject has no deadline or gets submitted before dealine

            // if($request->hasFile('files')){
            //     $file = $request->file('files');
            //     $file_name= $file->getClientOriginalName();
            //     $file->storeAs('public/uploads/answers',$file_name);
            // }else{

                //if statement checks if file is a file and is valid, otherwise no file to upload
            
                //     return "Failed to upload";
            // }
            
        $data=[
            'subject_id' => $request->subject_id,
            'admin_id' => Auth::user()->id,
            // 'files' => $file_name,
        ];
        $answer = Answer::create($data);  
        $answer->hash = Crypt::encrypt($answer->id);
        return view('admin.backend.answers.tus',compact('answer'));

        } else {
            // late submission won't be accepted
            Session::flash('flash_danger', 'Sorry... you missed the deadline for submission !');
            Session::flash('flash_type', 'alert-danger');
            return redirect()->route('admin.answers.index');
        }
        // $data=[
        //     'subject_id' => $request->subject_id,
        //     'admin_id' => Auth::user()->id,
        //     'files' => $file_name,
        // ];
        // $answer = Answer::create($data);
        // Session::flash('flash_success', 'Answer created successfully!.');
        // Session::flash('flash_type', 'alert-success');
        // return redirect()->route('admin.answers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Answer  $Answer
     * @return \Illuminate\Http\Response
     */
    public function show(Answer $answer)
    {
        //
        abort_if(Gate::denies('answer-show'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $answer->load('subject','user');
        return view('admin.backend.answers.show', compact('answer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Answer $answer)
    {
        //
        abort_if(Gate::denies('answer-edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $subjects = Subject::all()->pluck('title','id')->prepend('please select a subject...','');
        $answer->load('subject');
        return view('admin.backend.answers.edit', compact('answer','subjects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAnswerRequest $request, Answer $answer)
    {
         $data=[
            'subject_id' => $request->subject_id,
            'admin_id' => Auth::user()->id,
            // 'description' => $request->description
        ];
        $answer->update($data);

        Session::flash('flash_success', 'Answer updated successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.answers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Answer $answer)
    {
        //
        abort_if(Gate::denies('answer-delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $answer->delete();

        Session::flash('flash_danger', 'Answer has been deleted !.');
        Session::flash('flash_type', 'alert-danger');
        return back();
    }

    public function massDestroy(MassDestroyAnswerRequest $request)
    {
        Answer::whereIn('id', request('ids'))->delete();
        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function download($file) {
        return response()->download(storage_path("app/public/uploads/answers/{$file}"));
    }

    public function getSubject(Request $request)
    {
        $subject_id = $request->subjectId;
        return Subject::findOrFail($subject_id);
    }

    public function getSubjects(Request $request)
    {
        $grade_id = $request->gradeId;
        return Subject::where('grade_id',$grade_id)->get();
    }

    public function uploaded(Request $request){
        $id = Crypt::decrypt($request->hash);
        $answer = Answer::find($id);
        if($answer->is_uploaded){
            abort(404);
        }
        $answer->files = $request->filename;
        $answer->is_uploaded = 1;
        $answer->update();
        return response('200');
    }
    public function tusUpload($hash)
    {
        try {
            $id = Crypt::decrypt($hash);
        } catch (DecryptException $e) {
            abort(404);
        }
        $answer = Answer::find($id);
        if($answer->is_uploaded){
            abort(404);
        }
        $answer->hash = Crypt::encrypt($answer->id);
        return view('admin.backend.answers.tus',compact('answer'));
    }
}

resources/views/admin/backend/answers/create.blade.php
@extends('admin.backend.layouts.master')
@section('title','Add Answer')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.upload') }} {{ trans('cruds.answer.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.answers.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                {{-- <label class="" for="subject">{{ trans('cruds.question.fields.subject') }}</label> --}}
                {!! Form::label('program_id', trans('cruds.subject.fields.program'), ['class' => 'control-label required']) !!}
                {!! Form::select('program_id', $programs, old('program_id'), ['class' => 'form-control select2', 'required' => 'required']) !!}
                @if($errors->has('program_id'))
                    <span class="text-danger">{{ $errors->first('program_id') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.subject.fields.program_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="grade_id">{{ trans('cruds.subject.fields.grade') }}</label>
                <select class="form-control select2 {{ $errors->has('grade_id') ? 'is-invalid' : '' }}" name="grade_id" id="grade_id" required>
                        <option value="">Please select grade...</option>
                </select>
                @if($errors->has('grade_id'))
                    <span class="text-danger">{{ $errors->first('grade_id') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.subject.fields.grade_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="subject_id">{{ trans('cruds.answer.fields.subject') }}</label>
                <select class="form-control select2 {{ $errors->has('subject_id') ? 'is-invalid' : '' }}" name="subject_id" id="subject_id" required>
                        <option value="">Please select subject...</option>
                </select>
                @if($errors->has('subject_id'))
                    <span class="text-danger">{{ $errors->first('subject_id') }}</span>
                @endif
                <span class="help-block upload_overdue">{{ trans('cruds.answer.fields.subject_helper') }}</span>
            </div>

            {{-- <div class="form-group">
                <label class="required" for="files">{{ trans('cruds.answer.fields.answer') }}</label>
                <input class="form-control {{ $errors->has('files') ? 'is-invalid' : '' }}" type="file" name="files" id="files" value="{{ old('files', '') }}" multiple required>
                @if($errors->has('files'))
                    <span class="text-danger">{{ $errors->first('files') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.answer.fields.answer_helper') }}</span>
            </div> --}}

            <div class="form-group">
                <button class="btn btn-success" type="submit" id="upload">
                    {{-- {{ trans('global.upload') }} --}}
                    Choose file to upload
                </button>
                <a href="{{route('admin.answers.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
<script>
       // if changes is made on faculty selection
       $("#program_id").change(function(){
        var selected_id = $(this).val();
        $.ajax({
            cache:false,
            url: '{{ route('admin.subjects.getspecificgrades') }}',
            type: 'get',
            data: {programId:selected_id},
            dataType: 'json',
            beforeSend: function(request) {
                                return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                            },
            success:function(data){
                var len = data.length;
                $("#grade_id").empty();

                var grade = $("#grade_id").append("<option value=''>Please select grade...</option>");

                for( var i = 0; i<len; i++){
                    var id = data[i]['id'];
                    var name = data[i]['title'];
                    grade.append("<option value='"+id+"'>"+name+"</option>");
                }
            }
        });
    });

    // if changes is made on grade selection
    $("#grade_id").change(function(){
        var selected_id = $(this).val();
        $.ajax({
            cache:false,
            url: '{{ route('admin.answers.getspecificsubjects') }}',
            type: 'get',
            data: {gradeId:selected_id},
            dataType: 'json',
            beforeSend: function(request) {
                                return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                            },
            success:function(data){
                var len = data.length;
                $("#subject_id").empty();

                var subject = $("#subject_id").append("<option value=''>Please select subject...</option>");

                for( var i = 0; i<len; i++){
                    var id = data[i]['id'];
                    var name = data[i]['title'];
                    subject.append("<option value='"+id+"'>"+name+"</option>");
                }
            }
        });
    });

    $("#subject_id").change(function(){
        var currentTime = '<?php echo \Carbon\Carbon::now() ?>';
        var selected_id = $(this).val();
        if(selected_id){
            $.ajax({
                cache:false,
                url: '{{ route('admin.answers.getsubject') }}',
                type: 'get',
                data: {subjectId:selected_id},
                dataType: 'json',
                beforeSend: function(request) {
                                    return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                                },
                success:function(data){
                    var deadline = data['deadline'];
                    if(deadline){
                        if(currentTime < deadline) {
                            $("#upload").prop('disabled', false);
                            $(".upload_overdue").html('');
                        } else {
                            $(".upload_overdue").html('<p style="color:red;">Sorry... you missed the deadline for submission !</p>');
                            $("#upload").prop('disabled', true);
                        }
                    } else {
                        $(".upload_overdue").html('');
                        $("#upload").prop('disabled', false);
                    }
                }
            });
        }
    });
   </script>
@endsection

resources/views/admin/backend/answers/edit.blade.php
@extends('admin.backend.layouts.master')
@section('title','Edit Answer')

@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.answer.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.answers.update", [$answer->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="subject_id">{{ trans('cruds.answer.fields.subject') }}</label>
                <select class="form-control select2 {{ $errors->has('subject_id') ? 'is-invalid' : '' }}" name="subject_id" id="subject_id" required>
                    @foreach($subjects as $id => $subject)
                        <option value="{{ $id }}" {{ ($id === $answer->subject->id) ? 'selected' : '' }}>{{ $subject }}</option>
                    @endforeach
                </select>
                @if($errors->has('subject_id'))
                    <span class="text-danger">{{ $errors->first('subject_id') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.answer.fields.subject_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="answer">{{ trans('cruds.answer.fields.answer') }}</label>
                <input class="form-control {{ $errors->has('answer') ? 'is-invalid' : '' }}" type="file" name="answer" id="answer" value="{{ old('answer', '') }}" required>
                @if($errors->has('answer'))
                    <span class="text-danger">{{ $errors->first('answer') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.answer.fields.answer_helper') }}</span>
            </div>
            
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.answers.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/backend/answers/index.blade.php
@extends('admin.backend.layouts.master')
@section('title','Answer')

@section('content')
@can('answer-create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary" href="{{ route("admin.answers.create") }}">
                {{ trans('global.upload') }} {{ trans('cruds.answer.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.answer.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-answer">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.answer.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.answer.fields.subject') }}
                        </th>
                        <th>
                            {{ trans('cruds.answer.fields.college') }}
                        </th>
                        <th>
                            {{ trans('cruds.answer.fields.answer') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($answers as $key => $answer)
                        <tr data-entry-id="{{ $answer->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $loop->index + 1 ?? '' }}
                            </td>
                            <td>
                                {{ $answer->subject->title ?? '' }}
                            </td>
                            <td>
                                {{ $answer->user->name ?? '' }}
                            </td>
                            <td>
                                {{ $answer->files ?? '' }}
                                {{ $answer->expired }}
                            </td>
                            <td>
                                @can('answer-download')
                                    @if($answer->files)
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.answers.download', $answer->files) }}">
                                        {{ trans('global.download') }}
                                    </a>
                                    @endif
                                @endcan

                                @can('answer-show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.answers.show', $answer->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('answer-edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.answers.edit', $answer->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @if(! $answer->is_uploaded && ! $answer->expired)
                                <a class="btn btn-xs btn-info" href="{{ route('admin.answers.tus', $answer->hash) }}">
                                    Add Answer
                                </a>
                                @endif
                                @can('answer-delete')
                                    <form action="{{ route('admin.answers.destroy', $answer->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection


@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('answer-delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.answers.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': $('meta[name="csrf-token"]').attr('content')},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-answer:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection