routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
// Route::get('/storage/{extra}', function ($extra) {
//     return redirect("/public/storage/$extra");
//     })->where('extra', '.*');
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

     //change password
     Route::get('change-password', 'Admin\ChangePasswordController@create')->name('password.create');
     Route::post('change-password', 'Admin\ChangePasswordController@update')->name('password.update');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');

    // subjects
    Route::get('subjects/getspecificgrades','Admin\SubjectController@getGrades')->name('subjects.getspecificgrades');
    Route::delete('subjects/destroy', 'Admin\SubjectController@massDestroy')->name('subjects.massDestroy');
    Route::resource('subjects','Admin\SubjectController');

    // questions
    Route::delete('questions/destroy', 'Admin\QuestionController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions','Admin\QuestionController');
    Route::get('questions/download/{file}','Admin\QuestionController@download')->name('questions.download');

    // answers
    Route::get('answers/getspecificsubjects','Admin\AnswerController@getSubjects')->name('answers.getspecificsubjects');
    Route::get('answers/getsubject','Admin\AnswerController@getSubject')->name('answers.getsubject');
    Route::delete('answers/destroy', 'Admin\AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers','Admin\AnswerController');
    Route::get('answers/download/{file}','Admin\AnswerController@download')->name('answers.download');
    Route::post('answers/upload','Admin\AnswerController@uploaded')->name('answers.uploaded');
    Route::get('answers/upload/{hash}','Admin\AnswerController@tusUpload')->name('answers.tus');

    // programs
    Route::delete('programs/destroy', 'Admin\ProgramController@massDestroy')->name('programs.massDestroy');
    Route::resource('programs', 'Admin\ProgramController');

    // form
    Route::delete('forms/destroy', 'Admin\FormController@massDestroy')->name('forms.massDestroy');
    Route::resource('forms', 'Admin\FormController');
    Route::get('forms/{form}', 'Admin\FormController@generateform')->name('forms.generate');
    Route::get('forms/{form}/print', 'Admin\FormController@printform')->name('forms.print');
    Route::post('forms/print', 'Admin\FormController@printmultipleform')->name('forms.print.multiple');
    Route::post('forms/triplicate/print', 'Admin\FormController@printtriplicate')->name('forms.print.triplicate');
    Route::get('forms/{form}/print-studentdetails', 'Admin\FormController@printformdetails')->name('forms.print-student-details');
    Route::post('forms/print-studentdetails', 'Admin\FormController@printmultipleformdetails')->name('forms.print-multiple-student-details');

    Route::resource('faculty', 'Admin\FacultyController');
    Route::delete('faculties/destroy', 'Admin\FacultyController@massDestroy')->name('faculty.massDestroy');

    Route::get('levels/getspecificlevels','Admin\LevelsController@getlevels')->name('levels.getspecificlevels');
    Route::delete('levels/destroy', 'Admin\LevelsController@massDestroy')->name('levels.massDestroy');
    Route::resource('levels', 'Admin\LevelsController');
    Route::post('levels/addlevel','Admin\LevelsController@addLevel')->name('levels.addLevel');

    // Route::post('programtypes/addtype','ProgramTypesController@addType')->name('programtypes.addType');
    // Route::delete('programtypes/destroy', 'ProgramTypesController@massDestroy')->name('programtypes.massDestroy');
    // Route::resource('programtypes', 'ProgramTypesController');

    Route::get('courses/getspecificcourses','Admin\CoursesController@getCourses')->name('courses.getspecificcourses');
    Route::get('courses/getcoursetypes','Admin\CoursesController@getCourseTypes')->name('courses.getcoursetypes');
    Route::delete('courses/destroy', 'Admin\CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'Admin\CoursesController');
    // Route::post('programs/addprogram','Admin\ProgramsController@addProgram')->name('programs.addProgram');

    Route::get('subs/getspecificsubs','Admin\SubController@getSubs')->name('subs.getspecificsubs');
    Route::get('subs/getspecificsub','Admin\SubController@getSub')->name('subs.getspecificsub');
    Route::delete('subs/destroy', 'Admin\SubController@massDestroy')->name('subs.massDestroy');
    Route::resource('subs','Admin\SubController', [
        'except' => [ 'create' ]
    ]);
    Route::get('subs/create/{id}','Admin\SubController@create')->name('subs.create');
    Route::get('subs/{id}/list', 'Admin\SubController@courseSubjects')->name('subs.courseSubjects');


});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Question extends Model
{
    use SoftDeletes;

    protected $dates = [
      'created_at',
      'updated_at',
      'deleted_at',
  ];
  
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'subject_id', 'files', 'created_at', 'updated_at', 'deleted_at', 
    ];


    public function subject() {
       return $this->belongsTo(Subject::class);
    }
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Subject;
use Gate;
use Symfony\Component\HttpFoundation\Response;
use App\Http\Requests\StoreQuestionRequest;
use App\Http\Requests\UpdateQuestionRequest;
use App\Http\Requests\MassDestroyQuestionRequest;
use Session;
use Auth;

class QuestionController extends Controller
{

     public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        abort_if(Gate::denies('question-access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $questions = Question::with('subject')->get();
        // dd($questions);
        return view('admin.backend.questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        abort_if(Gate::denies('question-create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $subjects = Subject::all()->pluck('title','id')->prepend('please select a subject...','');        
        return view('admin.backend.questions.create', compact('subjects'));
  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreQuestionRequest $request)
    {
        // dd($request->file('files')->isValid());
        if($request->hasFile('files') && $request->file('files')->isValid()){
            $file = $request->file('files');
            $file_name= uniqid().'_'.$file->getClientOriginalName();
                $file->move(public_path().'/questions', $file_name);
                $files = $file_name;
        }else{
            //if statement checks if file is a file and is valid, otherwise no file to upload
            return "Failed to upload";

        }
        $data=[           
            'subject_id' => $request->subject_id,
            'files' => $files
        ];
        // dd($data);
        Question::create($data);    

        Session::flash('flash_success', 'Question created successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.questions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(question $question)
    {
        //
        abort_if(Gate::denies('question-show'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $question->load('subject');
        return view('admin.backend.questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(question $question)
    {
        //
        abort_if(Gate::denies('question-edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');                
        $subjects = Subject::all()->pluck('title','id')->prepend('please select a subject...','');        
        $question->load('subject');
        // dd($question);
        return view('admin.backend.questions.edit', compact('question','subjects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionRequest $request, question $question)
    {    
        //  dd($request->all());
         $data=[
            'subject_id' => $request->subject_id,
            // 'description' => $request->description
        ];
        $question->update($data);        

        Session::flash('flash_success', 'Question updated successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.questions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(question $question)
    {
        //
        abort_if(Gate::denies('question-delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $question->delete();

        Session::flash('flash_danger', 'Question has been deleted !.');
        Session::flash('flash_type', 'alert-danger');
        return back();
    }

    public function massDestroy(MassDestroyQuestionRequest $request)
    {
        Question::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }

    public function download($file) {
        return response()->download(public_path("questions/{$file}"));
    }
}

resources/views/admin/backend/questions/create.blade.php
@extends('admin.backend.layouts.master')
@section('title','Add Question')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.add') }} {{ trans('cruds.question.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.questions.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                {{-- <label class="" for="subject">{{ trans('cruds.question.fields.subject') }}</label> --}}
                {!! Form::label('subject_id', trans('cruds.question.fields.subject'), ['class' => 'control-label required']) !!}
                {!! Form::select('subject_id', $subjects, old('subject_id'), ['class' => 'form-control select2']) !!}
                @if($errors->has('subject_id'))
                    <span class="text-danger">{{ $errors->first('subject_id') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.question.fields.subject_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="files">{{ trans('cruds.question.fields.question') }}</label>
                <input class="form-control {{ $errors->has('files') ? 'is-invalid' : '' }}" type="file" name="files" id="files" value="{{ old('files', '') }}" required>
                @if($errors->has('files'))
                    <span class="text-danger">{{ $errors->first('files') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.question.fields.question_helper') }}</span>
            </div>
            
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.questions.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
   
@endsection

resources/views/admin/backend/questions/edit.blade.php
@extends('admin.backend.layouts.master')
@section('title','Edit Question')

@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.question.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.questions.update", [$question->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="subject_id">{{ trans('cruds.question.fields.subject') }}</label>
                <select class="form-control select2 {{ $errors->has('subject_id') ? 'is-invalid' : '' }}" name="subject_id" id="subject_id" required>
                    @foreach($subjects as $id => $subject)
                        <option value="{{ $id }}" {{ ($id === $question->subject->id) ? 'selected' : '' }}>{{ $subject }}</option>
                    @endforeach
                </select>
                @if($errors->has('subject_id'))
                    <span class="text-danger">{{ $errors->first('subject_id') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.question.fields.subject_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="question">{{ trans('cruds.question.fields.question') }}</label>
                <input class="form-control {{ $errors->has('question') ? 'is-invalid' : '' }}" type="file" name="question" id="question" value="{{ old('question', '') }}" required>
                @if($errors->has('question'))
                    <span class="text-danger">{{ $errors->first('question') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.question.fields.question_helper') }}</span>
            </div>
            
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.questions.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/backend/questions/index.blade.php
@extends('admin.backend.layouts.master')
@section('title','Question')

@section('content')
@can('question-create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary" href="{{ route("admin.questions.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.question.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.question.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-question">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.question.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.question.fields.subject') }}
                        </th>
                        <th>
                            {{ trans('cruds.question.fields.question') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($questions as $key => $question)
                        <tr data-entry-id="{{ $question->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $loop->index + 1 ?? '' }}
                            </td>
                            <td>
                                {{ $question->subject->title ?? '' }}
                            </td>
                            <td>
                                {{ $question->files ?? '' }}
                            </td>
                            <td>
                                @can('question-download')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.questions.download', $question->files) }}">
                                        {{ trans('global.download') }}
                                    </a>
                                @endcan
                                @can('question-show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.questions.show', $question->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('question-edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.questions.edit', $question->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('question-delete')
                                    <form action="{{ route('admin.questions.destroy', $question->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection


@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('question-delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.questions.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': $('meta[name="csrf-token"]').attr('content')},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-question:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/backend/questions/show.blade.php
@extends('admin.backend.layouts.master')
@section('title','View Question')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.question.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            
            <table class="table table-bordered table-striped">
                <tbody>
                   
                    <tr>
                        <th>
                            {{ trans('cruds.question.fields.subject') }}
                        </th>
                        <td>
                            {{ $question->subject->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.question.fields.question') }}
                        </th>
                        <td>
                            {{ $question->files }}
                        </td>
                    </tr>
                   
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.questions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection