routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
// Route::get('/storage/{extra}', function ($extra) {
//     return redirect("/public/storage/$extra");
//     })->where('extra', '.*');
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

     //change password
     Route::get('change-password', 'Admin\ChangePasswordController@create')->name('password.create');
     Route::post('change-password', 'Admin\ChangePasswordController@update')->name('password.update');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');

    // subjects
    Route::get('subjects/getspecificgrades','Admin\SubjectController@getGrades')->name('subjects.getspecificgrades');
    Route::delete('subjects/destroy', 'Admin\SubjectController@massDestroy')->name('subjects.massDestroy');
    Route::resource('subjects','Admin\SubjectController');

    // questions
    Route::delete('questions/destroy', 'Admin\QuestionController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions','Admin\QuestionController');
    Route::get('questions/download/{file}','Admin\QuestionController@download')->name('questions.download');

    // answers
    Route::get('answers/getspecificsubjects','Admin\AnswerController@getSubjects')->name('answers.getspecificsubjects');
    Route::get('answers/getsubject','Admin\AnswerController@getSubject')->name('answers.getsubject');
    Route::delete('answers/destroy', 'Admin\AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers','Admin\AnswerController');
    Route::get('answers/download/{file}','Admin\AnswerController@download')->name('answers.download');
    Route::post('answers/upload','Admin\AnswerController@uploaded')->name('answers.uploaded');
    Route::get('answers/upload/{hash}','Admin\AnswerController@tusUpload')->name('answers.tus');

    // programs
    Route::delete('programs/destroy', 'Admin\ProgramController@massDestroy')->name('programs.massDestroy');
    Route::resource('programs', 'Admin\ProgramController');

    // form
    Route::delete('forms/destroy', 'Admin\FormController@massDestroy')->name('forms.massDestroy');
    Route::resource('forms', 'Admin\FormController');
    Route::get('forms/{form}', 'Admin\FormController@generateform')->name('forms.generate');
    Route::get('forms/{form}/print', 'Admin\FormController@printform')->name('forms.print');
    Route::post('forms/print', 'Admin\FormController@printmultipleform')->name('forms.print.multiple');
    Route::post('forms/triplicate/print', 'Admin\FormController@printtriplicate')->name('forms.print.triplicate');
    Route::get('forms/{form}/print-studentdetails', 'Admin\FormController@printformdetails')->name('forms.print-student-details');
    Route::post('forms/print-studentdetails', 'Admin\FormController@printmultipleformdetails')->name('forms.print-multiple-student-details');

    Route::resource('faculty', 'Admin\FacultyController');
    Route::delete('faculties/destroy', 'Admin\FacultyController@massDestroy')->name('faculty.massDestroy');

    Route::get('levels/getspecificlevels','Admin\LevelsController@getlevels')->name('levels.getspecificlevels');
    Route::delete('levels/destroy', 'Admin\LevelsController@massDestroy')->name('levels.massDestroy');
    Route::resource('levels', 'Admin\LevelsController');
    Route::post('levels/addlevel','Admin\LevelsController@addLevel')->name('levels.addLevel');

    // Route::post('programtypes/addtype','ProgramTypesController@addType')->name('programtypes.addType');
    // Route::delete('programtypes/destroy', 'ProgramTypesController@massDestroy')->name('programtypes.massDestroy');
    // Route::resource('programtypes', 'ProgramTypesController');

    Route::get('courses/getspecificcourses','Admin\CoursesController@getCourses')->name('courses.getspecificcourses');
    Route::get('courses/getcoursetypes','Admin\CoursesController@getCourseTypes')->name('courses.getcoursetypes');
    Route::delete('courses/destroy', 'Admin\CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'Admin\CoursesController');
    // Route::post('programs/addprogram','Admin\ProgramsController@addProgram')->name('programs.addProgram');

    Route::get('subs/getspecificsubs','Admin\SubController@getSubs')->name('subs.getspecificsubs');
    Route::get('subs/getspecificsub','Admin\SubController@getSub')->name('subs.getspecificsub');
    Route::delete('subs/destroy', 'Admin\SubController@massDestroy')->name('subs.massDestroy');
    Route::resource('subs','Admin\SubController', [
        'except' => [ 'create' ]
    ]);
    Route::get('subs/create/{id}','Admin\SubController@create')->name('subs.create');
    Route::get('subs/{id}/list', 'Admin\SubController@courseSubjects')->name('subs.courseSubjects');


});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    //
    use SoftDeletes;

    protected $dates = [
      'created_at',
      'updated_at',
      'deleted_at',
  ];
  
    protected $fillable = [
        'title',
        'slug',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function permissions() {

        return $this->belongsToMany(Permission::class,'roles_permissions');
            
     }
     
     public function admins() {
     
        return $this->belongsToMany(Admin::class,'admins_roles');
            
     }

     public function getRouteKeyName() {
         return 'slug';
     }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Role;
use App\Permission;
use Gate;
use Symfony\Component\HttpFoundation\Response;
use App\Http\Requests\StoreRoleRequest;
use App\Http\Requests\UpdateRoleRequest;
use App\Http\Requests\MassDestroyRoleRequest;
use Session;
use Auth;

class RolesController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    //
    public function index()
    {
       
        abort_if(Gate::denies('role-access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $auth_roles = Auth::user()->roles()->pluck('title');
        
        //getting only accessible courses for user group
        foreach($auth_roles as $key => $role){
            if($role == 'IT Admin'){
                $roles = Role::all();
                break;
            }
            else{
                $roles = Role::where('title','!=','IT Admin')->get();
            }
        }

        return view('admin.backend.roles.index', compact('roles'));
    }

    public function create()
    {
        abort_if(Gate::denies('role-create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $permissions = Permission::pluck('title', 'id');
        return view('admin.backend.roles.create',compact('permissions'));
    }

    public function store(StoreRoleRequest $request)
    {
        // dd($request->all());
        $data=[
            'title' => $request->title,
            'slug' => str_slug($request->title)
        ];
        // dd($data);
        $role = Role::create($data);
        $role->permissions()->sync($request->input('permissions', []));

        Session::flash('flash_success', 'Role created successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.roles.index');

    }

    public function edit(Role $role)
    {
        abort_if(Gate::denies('role-edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $permissions = Permission::all()->pluck('title', 'id');
        $role->load('permissions');

        return view('admin.backend.roles.edit', compact('role','permissions'));
    }

    public function update(UpdateRoleRequest $request, Role $role)
    {
        // dd($request);
        $data=[
            'title' => $request->title,
            'slug' => str_slug($request->title)
        ];
        // dd($data);
        $role->update($data);
        $role->permissions()->sync($request->input('permissions', []));

        Session::flash('flash_success', 'Role updated successfully!.');
        Session::flash('flash_type', 'alert-success');
        return redirect()->route('admin.roles.index');

    }

    public function show(Role $role)
    {
        abort_if(Gate::denies('role-show'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $role->load('permissions');
        
        return view('admin.backend.roles.show', compact('role'));
    }

    public function destroy(Role $role)
    {
        abort_if(Gate::denies('role-delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $role->delete();

        Session::flash('flash_danger', 'Role has been deleted !.');
        Session::flash('flash_type', 'alert-danger');
        return back();

    }

    public function massDestroy(MassDestroyRoleRequest $request)
    {
        Role::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);

    }
}

resources/views/admin/backend/roles/create.blade.php
@extends('admin.backend.layouts.master')
@section('title','Add Role')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.role.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.roles.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="title">{{ trans('cruds.role.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.role.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="permissions">{{ trans('cruds.role.fields.permissions') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('permissions') ? 'is-invalid' : '' }}" name="permissions[]" id="permissions" multiple required>
                    @foreach($permissions as $id => $permissions)
                        @foreach(Auth::user()->roles->pluck('title') as $roles)
                            @if($roles == 'Admin' && (substr($permissions, 0, 11) != 'permission_'))
                                <option value="{{ $id }}" {{ in_array($id, old('permissions', [])) ? 'selected' : '' }}>{{ $permissions }}</option>
                            @elseif($roles == 'IT Admin')
                                <option value="{{ $id }}" {{ in_array($id, old('permissions', [])) ? 'selected' : '' }}>{{ $permissions }}</option>
                            @endif
                        @endforeach
                    @endforeach
                </select>
                @if($errors->has('permissions'))
                    <span class="text-danger">{{ $errors->first('permissions') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.role.fields.permissions_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.roles.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/backend/roles/edit.blade.php
@extends('admin.backend.layouts.master')
@section('title','Edit Role')

@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.role.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.roles.update", [$role->slug]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="title">{{ trans('cruds.role.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $role->title) }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.role.fields.title_helper') }}</span>
            </div>
             <div class="form-group">
                <label class="required" for="permissions">{{ trans('cruds.role.fields.permissions') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('permissions') ? 'is-invalid' : '' }}" name="permissions[]" id="permissions" multiple required>
                    @foreach($permissions as $id => $permissions)
                        @foreach(Auth::user()->roles->pluck('title') as $roles)
                            @if($roles == 'Admin' && (substr($permissions, 0, 11) != 'permission_'))
                            <option value="{{ $id }}" {{ (in_array($id, old('permissions', [])) || $role->permissions->contains($id)) ? 'selected' : '' }}>{{ $permissions }}</option>
                            @elseif($roles == 'IT Admin')
                            <option value="{{ $id }}" {{ (in_array($id, old('permissions', [])) || $role->permissions->contains($id)) ? 'selected' : '' }}>{{ $permissions }}</option>
                            @endif
                        @endforeach
                       
                    @endforeach
                </select>
                @if($errors->has('permissions'))
                    <span class="text-danger">{{ $errors->first('permissions') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.role.fields.permissions_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    {{ trans('global.save') }}
                </button>
                <a href="{{route('admin.roles.index')}}" class="btn btn-danger">{{ trans('global.cancel') }}</a>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/backend/roles/index.blade.php
@extends('admin.backend.layouts.master')
@section('title','Role')

@section('content')
@can('role-create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary" href="{{ route("admin.roles.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.role.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.role.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Role">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.role.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.role.fields.title') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($roles as $key => $role)
                        <tr data-entry-id="{{ $role->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $loop->index + 1 ?? '' }}
                            </td>
                            <td>
                                {{ $role->title ?? '' }}
                            </td>
                            <td>
                                @can('role-show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.roles.show', $role->slug) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('role-edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.roles.edit', $role->slug) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('role-delete')
                                    <form action="{{ route('admin.roles.destroy', $role->slug) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection


@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('role-delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.roles.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': $('meta[name="csrf-token"]').attr('content')},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Role:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/backend/roles/show.blade.php
@extends('admin.backend.layouts.master')
@section('title','View Role')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.role.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            
            <table class="table table-bordered table-striped">
                <tbody>
                    
                    <tr>
                        <th>
                            {{ trans('cruds.role.fields.title') }}
                        </th>
                        <td>
                            {{ $role->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.role.fields.permissions') }}
                        </th>
                        <td>
                            @foreach($role->permissions as $key => $permissions)
                                <span class="badge badge-info">{{ $permissions->title }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.roles.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection