routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'Admin\HomeController@index')->name('dashboard');
// Route::get('/storage/{extra}', function ($extra) {
//     return redirect("/public/storage/$extra");
//     })->where('extra', '.*');
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');

     //change password
     Route::get('change-password', 'Admin\ChangePasswordController@create')->name('password.create');
     Route::post('change-password', 'Admin\ChangePasswordController@update')->name('password.update');

    //password reset routes
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');

    // Permissions
    Route::delete('permissions/destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'Admin\PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'Admin\RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'Admin\RolesController');

    // Users
    Route::delete('users/destroy', 'Admin\UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'Admin\UsersController');

    // groups
    Route::delete('groups/destroy', 'Admin\GroupsController@massDestroy')->name('groups.massDestroy');
    Route::resource('groups', 'Admin\GroupsController');

    // subjects
    Route::get('subjects/getspecificgrades','Admin\SubjectController@getGrades')->name('subjects.getspecificgrades');
    Route::delete('subjects/destroy', 'Admin\SubjectController@massDestroy')->name('subjects.massDestroy');
    Route::resource('subjects','Admin\SubjectController');

    // questions
    Route::delete('questions/destroy', 'Admin\QuestionController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions','Admin\QuestionController');
    Route::get('questions/download/{file}','Admin\QuestionController@download')->name('questions.download');

    // answers
    Route::get('answers/getspecificsubjects','Admin\AnswerController@getSubjects')->name('answers.getspecificsubjects');
    Route::get('answers/getsubject','Admin\AnswerController@getSubject')->name('answers.getsubject');
    Route::delete('answers/destroy', 'Admin\AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers','Admin\AnswerController');
    Route::get('answers/download/{file}','Admin\AnswerController@download')->name('answers.download');
    Route::post('answers/upload','Admin\AnswerController@uploaded')->name('answers.uploaded');
    Route::get('answers/upload/{hash}','Admin\AnswerController@tusUpload')->name('answers.tus');

    // programs
    Route::delete('programs/destroy', 'Admin\ProgramController@massDestroy')->name('programs.massDestroy');
    Route::resource('programs', 'Admin\ProgramController');

    // form
    Route::delete('forms/destroy', 'Admin\FormController@massDestroy')->name('forms.massDestroy');
    Route::resource('forms', 'Admin\FormController');
    Route::get('forms/{form}', 'Admin\FormController@generateform')->name('forms.generate');
    Route::get('forms/{form}/print', 'Admin\FormController@printform')->name('forms.print');
    Route::post('forms/print', 'Admin\FormController@printmultipleform')->name('forms.print.multiple');
    Route::post('forms/triplicate/print', 'Admin\FormController@printtriplicate')->name('forms.print.triplicate');
    Route::get('forms/{form}/print-studentdetails', 'Admin\FormController@printformdetails')->name('forms.print-student-details');
    Route::post('forms/print-studentdetails', 'Admin\FormController@printmultipleformdetails')->name('forms.print-multiple-student-details');

    Route::resource('faculty', 'Admin\FacultyController');
    Route::delete('faculties/destroy', 'Admin\FacultyController@massDestroy')->name('faculty.massDestroy');

    Route::get('levels/getspecificlevels','Admin\LevelsController@getlevels')->name('levels.getspecificlevels');
    Route::delete('levels/destroy', 'Admin\LevelsController@massDestroy')->name('levels.massDestroy');
    Route::resource('levels', 'Admin\LevelsController');
    Route::post('levels/addlevel','Admin\LevelsController@addLevel')->name('levels.addLevel');

    // Route::post('programtypes/addtype','ProgramTypesController@addType')->name('programtypes.addType');
    // Route::delete('programtypes/destroy', 'ProgramTypesController@massDestroy')->name('programtypes.massDestroy');
    // Route::resource('programtypes', 'ProgramTypesController');

    Route::get('courses/getspecificcourses','Admin\CoursesController@getCourses')->name('courses.getspecificcourses');
    Route::get('courses/getcoursetypes','Admin\CoursesController@getCourseTypes')->name('courses.getcoursetypes');
    Route::delete('courses/destroy', 'Admin\CoursesController@massDestroy')->name('courses.massDestroy');
    Route::resource('courses', 'Admin\CoursesController');
    // Route::post('programs/addprogram','Admin\ProgramsController@addProgram')->name('programs.addProgram');

    Route::get('subs/getspecificsubs','Admin\SubController@getSubs')->name('subs.getspecificsubs');
    Route::get('subs/getspecificsub','Admin\SubController@getSub')->name('subs.getspecificsub');
    Route::delete('subs/destroy', 'Admin\SubController@massDestroy')->name('subs.massDestroy');
    Route::resource('subs','Admin\SubController', [
        'except' => [ 'create' ]
    ]);
    Route::get('subs/create/{id}','Admin\SubController@create')->name('subs.create');
    Route::get('subs/{id}/list', 'Admin\SubController@courseSubjects')->name('subs.courseSubjects');


});

resources/views/admin/backend/layouts/error.blade.php
@if(count($errors) > 0)
<div class="form-group">
        <div class="col-md-12">
    @foreach($errors->all() as $error)
        <p class="alert alert-danger">{{ $error}}</p>
    @endforeach
    </div>
    </div>
@endif

resources/views/admin/backend/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; <a href="http://egskill.com">egskill</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
</footer>

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('/backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('/backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('/backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{ asset('/backend/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{ asset('/backend/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
{{-- <script src="{{ asset('/backend/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{ asset('/backend/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script> --}}
<!-- jQuery Knob Chart -->
<script src="{{ asset('/backend/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<script src="{{ asset('/backend/plugins/moment/moment.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{ asset('/backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- datepicker -->
<script src="{{ asset('/backend/plugins/datepicker/js/bootstrap-datepicker.min.js')}}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('/backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{ asset('/backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('/backend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('/backend/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{ asset('/backend/dist/js/pages/dashboard.js')}}"></script> --}}
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('/backend/dist/js/demo.js')}}"></script>
<script src="{{ asset('/js/printThis.js')}}"></script>
<script src="{{ asset('/backend/js/select-all.js')}}"></script>
<script src="{{ asset('/backend/bower_components/select2/dist/js/select2.full.min.js')}}"></script>
<script src="https://unpkg.com/nepali-date-picker@2.0.1/dist/jquery.nepaliDatePicker.min.js" crossorigin="anonymous"></script>
<!-- dataTable -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.3.0/js/dataTables.select.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.flash.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.colVis.min.js"></script>


<script>
  $(document).ready(function(){
      setTimeout(function(){
         $(".alert").remove();
      }, 5000 ); // 5 secs

  });

  $(document).ready(function(){
      $('.select2').select2({
        theme:'bootstrap4',
      });
  });


          // yajradatatables

    $(function() {
  let copyButtonTrans = '{{ trans('global.datatables.copy') }}'
  let csvButtonTrans = '{{ trans('global.datatables.csv') }}'
  let excelButtonTrans = '{{ trans('global.datatables.excel') }}'
  let pdfButtonTrans = '{{ trans('global.datatables.pdf') }}'
  let printButtonTrans = '{{ trans('global.datatables.print') }}'
  let colvisButtonTrans = '{{ trans('global.datatables.colvis') }}'
  let selectAllButtonTrans = '{{ trans('global.select_all') }}'
  let selectNoneButtonTrans = '{{ trans('global.deselect_all') }}'

  let languages = {
  'en': 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/English.json'
  };

  $.extend(true, $.fn.dataTable.Buttons.defaults.dom.button, { className: 'btn' })
  $.extend(true, $.fn.dataTable.defaults, {
  language: {
  url: languages['{{ app()->getLocale() }}']
  },
  columnDefs: [{
    orderable: false,
    className: 'select-checkbox',
    targets: 0
  }, {
    orderable: false,
    searchable: false,
    targets: -1
  }],
  select: {
  style:    'multi+shift',
  selector: 'td:first-child'
  },
  order: [],
  scrollX: true,
  pageLength: 100,
  dom: 'lBfrtip<"actions">',
  buttons: [
  {
    extend: 'selectAll',
    className: 'btn-primary',
    text: selectAllButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'selectNone',
    className: 'btn-primary',
    text: selectNoneButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'copy',
    className: 'btn-default',
    text: copyButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'csv',
    className: 'btn-default',
    text: csvButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'excel',
    className: 'btn-default',
    text: excelButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'pdf',
    className: 'btn-default',
    text: pdfButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'print',
    className: 'btn-default',
    text: printButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  },
  {
    extend: 'colvis',
    className: 'btn-default',
    text: colvisButtonTrans,
    exportOptions: {
      columns: ':visible'
    }
  }
  ]
  });

  $.fn.dataTable.ext.classes.sPageButton = '';
  });
  

</script>

@yield('scripts')

resources/views/admin/backend/layouts/head.blade.php
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title') | egskill</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {{-- csrf-token for ajax post request --}}
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('/backend/plugins/fontawesome-free/css/all.min.css')}}">

  <!-- Ionicons -->
  {{-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"> --}}
  <!-- Tempusdominus Bbootstrap 4 -->
  {{-- <link rel="stylesheet" href="{{asset('/backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}"> --}}
  <!-- iCheck -->
  {{-- <link rel="stylesheet" href="{{asset('/backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}"> --}}
  <!-- JQVMap -->
  {{-- <link rel="stylesheet" href="{{asset('/backend/plugins/jqvmap/jqvmap.min.css')}}"> --}}
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('/backend/dist/css/adminlte.min.css')}}">
  <link href="{{ asset('css/custom.css') }}" rel="stylesheet" />
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('/backend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{asset('/backend/plugins/daterangepicker/daterangepicker.css')}}">
  <!-- datepicker -->
  <link rel="stylesheet" href="{{asset('/backend/plugins/datepicker/css/bootstrap-datepicker3.min.css')}}">

  <link rel="stylesheet" href="{{ asset('/backend/bower_components/select2/dist/css/select2.min.css')}}">
  <link rel="stylesheet" href="{{ asset('/backend/plugins/select2/css/select2.bootstrap.min.css')}}">

  <!-- dataTables -->
  {{-- <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" /> --}}
  <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
  <link href="https://cdn.datatables.net/select/1.3.0/css/select.dataTables.min.css" rel="stylesheet" />
  <link href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css" rel="stylesheet" />

  <!-- summernote -->
  {{-- <link rel="stylesheet" href="{{asset('/backend/plugins/summernote/summernote-bs4.css')}}"> --}}
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/nepali-date-picker@2.0.1/dist/nepaliDatePicker.min.css" crossorigin="anonymous" />

  @yield('styles')

resources/views/admin/backend/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('admin.backend.layouts.head')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <div class="loading">
        <img class="loading-gif" src="{{ asset ('loading.gif') }}">
    </div>
  <!-- Navbar -->
  @include('admin.backend.layouts.nav')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    @include('admin.backend.layouts.sidebar')
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <section class="content" style="padding-top: 20px">
    <!-- Content Header (Page header) -->
    {{-- <div class="content-header">

    </div> --}}
    <!-- /.content-header -->
    <div class="col-lg-8">
      @include('admin.backend.includes.messages')
    </div>
      @section('content')
        @show
    <!-- /.content -->
    </section>
  </div>
  <!-- /.content-wrapper -->
  @include('admin.backend.layouts.footer')
</body>
<script>
    $(document).ready(function() {
        $('.loading').addClass('d-none');
    });
</script>
</html>

resources/views/admin/backend/layouts/nav.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      {{-- <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('admin.dashboard')}}" class="nav-link">Home</a>
      </li> --}}
      
    </ul>

    <!-- SEARCH FORM -->
    {{-- <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form> --}}

    <!-- Right navbar links -->
    {{-- <ul class="navbar-nav ml-auto">
            
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul> --}}
  </nav>

resources/views/admin/backend/layouts/sidebar.blade.php
<!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{ asset('/backend/dist/img/AdminLTELogo.png')}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="{{ route('admin.dashboard')}}" class="d-block">{{Auth::user()->name}}</a>
      </div>
    </div>

    
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
      
        <li class="nav-item">
          <a href="{{ route('admin.dashboard')}}" class="nav-link {{ (request()->is('/admin')) ? 'active' : '' }}">
            <p>
            <i class="nav-icon fas fa-tachometer-alt"></i>
             <span> {{ trans('global.dashboard') }} </span>
            </p>
          </a>
        </li>
        
        @foreach(Auth::user()->groups as $group)
        @if($group->title==='Owner')
            @can('user-management-access')
            <li class="nav-item has-treeview {{ request()->is('admin/permissions*') ? 'menu-open' : '' }} {{ request()->is('admin/roles*') ? 'menu-open' : '' }} {{ request()->is('admin/groups*') ? 'menu-open' : '' }} {{ request()->is('admin/users*') ? 'menu-open' : '' }}">
                <a class="nav-link nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-users">

                    </i>
                    <p>
                        <span>{{ trans('cruds.userManagement.title') }}</span>
                        <i class="right fa fa-fw fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    @can('permission-access')
                        <li class="nav-item">
                            <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                <i class="fa-fw fas fa-unlock-alt">

                                </i>
                                <p>
                                    <span>{{ trans('cruds.permission.title') }}</span>
                                </p>
                            </a>
                        </li>
                    @endcan
                    @can('role-access')
                        <li class="nav-item">
                            <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                <i class="fa-fw fas fa-briefcase">

                                </i>
                                <p>
                                    <span>{{ trans('cruds.role.title') }}</span>
                                </p>
                            </a>
                        </li>
                    @endcan
                    @can('group-access')
                      <li class="nav-item">
                          <a href="{{ route("admin.groups.index") }}" class="nav-link {{ request()->is('admin/groups') || request()->is('admin/groups/*') ? 'active' : '' }}">
                            <i class="fas fa-user-friends"></i>
                              <p>
                                  <span>{{ trans('cruds.group.title') }}</span>
                              </p>
                          </a>
                      </li>
                    @endcan
                    @can('user-access')
                        <li class="nav-item">
                            <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                <i class="fa-fw fas fa-user">

                                </i>
                                <p>
                                    <span>{{ trans('cruds.user.title') }}</span>
                                </p>
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan

    {{-- additional menu goes here --}}
    @can('faculty-access')
      <li class="nav-item">
          <a href="{{ route("admin.faculty.index") }}" class="nav-link {{ request()->is('admin/faculty') || request()->is('admin/faculty/*') ? 'active' : '' }}">
            <i class="fas fa-university">

              </i>
              <p>
                  <span>{{ trans('cruds.faculty.title') }}</span>
              </p>
          </a>
      </li>
    @endcan

    @can('level-access')
      <li class="nav-item">
          <a href="{{ route("admin.levels.index") }}" class="nav-link {{ request()->is('admin/levels') || request()->is('admin/levels/*') ? 'active' : '' }}">
            <i class="fas fa-university">

              </i>
              <p>
                  <span>{{ trans('cruds.level.title') }}</span>
              </p>
          </a>
      </li>
    @endcan

    @can('course-access')
      <li class="nav-item">
          <a href="{{ route("admin.courses.index") }}" class="nav-link {{ request()->is('admin/courses') || request()->is('admin/courses/*') || request()->is('admin/subs/*') ? 'active' : '' }}">
            <i class="fas fa-university">

              </i>
              <p>
                  <span>{{ trans('cruds.program.title') }}</span>
              </p>
          </a>
      </li>
    @endcan
@endif
@endforeach
    {{-- @can('sub-access')
      <li class="nav-item">
          <a href="{{ route("admin.subs.index") }}" class="nav-link {{ request()->is('admin/subs') || request()->is('admin/subs/*') ? 'active' : '' }}">
            <i class="fas fa-university">

              </i>
              <p>
                  <span>{{ trans('cruds.sub.title') }}</span>
              </p>
          </a>
      </li>
    @endcan --}}

  @can('program-access')
    <li class="nav-item">
      <a href="{{ route('admin.programs.index') }}" class="nav-link {{ request()->is('admin/programs') || request()->is('admin/programs/*') ? 'active' : '' }}">
          <i class="fa fa-book"></i>
          <p> <span>{{ trans('cruds.program.title') }}</span></p>
      </a>
    </li>
    @endcan
    @can('subject-access')
    <li class="nav-item">
      <a href="{{ route('admin.subjects.index') }}" class="nav-link {{ request()->is('admin/subjects') || request()->is('admin/subjects/*') ? 'active' : '' }}">
          <i class="fa fa-book"></i>
          <p> <span>{{ trans('cruds.subject.title') }}</span></p>
      </a>
    </li>
    @endcan
    @can('question-access')
    <li class="nav-item">
      <a href="{{ route('admin.questions.index') }}" class="nav-link {{ request()->is('admin/questions') || request()->is('admin/questions/*') ? 'active' : '' }}">
          <i class="fa fa-question"></i>
          <p> <span>{{ trans('cruds.question.title') }}</span></p>
      </a>
    </li>
    @endcan
    @can('answer-access')
    <li class="nav-item">
      <a href="{{ route('admin.answers.index') }}" class="nav-link {{ request()->is('admin/answers') || request()->is('admin/answers/*') ? 'active' : '' }}">
          <i class="fa fa-plus-circle"></i>
          <p> <span>{{ trans('cruds.answer.title') }}</span></p>
      </a>
    </li>
    @endcan
    @can('form-access')
    <li class="nav-item">
      <a href="{{ route('admin.forms.index') }}" class="nav-link {{ request()->is('admin/forms') || request()->is('admin/forms/*') ? 'active' : '' }}">
          <i class="fa fa-plus-circle"></i>
          <p> <span>Applicants</span></p>
      </a>
    </li>
    @endcan


    {{-- menu to change password --}}
        <li class="nav-item">
          <a href="{{ route('admin.password.create') }}" class="nav-link {{ request()->is('admin/change-password') || request()->is('admin/change-password/*') ? 'active' : '' }}">
              <i class="fa fa-key"></i>
              <p> <span>{{ trans('global.change_password') }}</span></p>
          </a>
        </li>
       
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>

  <div class="sidebar sidebar_footer" style="text-align:center;">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <li class="nav-item">
        <a href="{{route('admin.logout')}}" class="nav-link">
          <p>
          <i class="nav-icon fas fa-sign-out-alt"></i>
            <span>{{trans('global.logout')}}</span>
          </p>
        </a>
      </li>
    </ul>
  </div>
  <!-- /.sidebar -->